# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Equipment.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_EquipmentDialog(object):
    def setupUi(self, EquipmentDialog):
        EquipmentDialog.setObjectName("EquipmentDialog")
        EquipmentDialog.resize(416, 343)
        EquipmentDialog.setMaximumSize(QtCore.QSize(416, 16777215))
        self.verticalLayout = QtWidgets.QVBoxLayout(EquipmentDialog)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_grade = QtWidgets.QHBoxLayout()
        self.horizontalLayout_grade.setObjectName("horizontalLayout_grade")
        self.label_grade = QtWidgets.QLabel(EquipmentDialog)
        self.label_grade.setObjectName("label_grade")
        self.horizontalLayout_grade.addWidget(self.label_grade)
        self.comboBox_grade = QtWidgets.QComboBox(EquipmentDialog)
        self.comboBox_grade.setObjectName("comboBox_grade")
        self.comboBox_grade.addItem("")
        self.horizontalLayout_grade.addWidget(self.comboBox_grade)
        self.horizontalLayout.addLayout(self.horizontalLayout_grade)
        self.horizontalLayout_level = QtWidgets.QHBoxLayout()
        self.horizontalLayout_level.setObjectName("horizontalLayout_level")
        self.label_level = QtWidgets.QLabel(EquipmentDialog)
        self.label_level.setObjectName("label_level")
        self.horizontalLayout_level.addWidget(self.label_level)
        self.comboBox_level = QtWidgets.QComboBox(EquipmentDialog)
        self.comboBox_level.setObjectName("comboBox_level")
        self.comboBox_level.addItem("")
        self.comboBox_level.addItem("")
        self.comboBox_level.addItem("")
        self.horizontalLayout_level.addWidget(self.comboBox_level)
        self.horizontalLayout.addLayout(self.horizontalLayout_level)
        self.horizontalLayout_type = QtWidgets.QHBoxLayout()
        self.horizontalLayout_type.setObjectName("horizontalLayout_type")
        self.label_type = QtWidgets.QLabel(EquipmentDialog)
        self.label_type.setObjectName("label_type")
        self.horizontalLayout_type.addWidget(self.label_type)
        self.comboBox_type = QtWidgets.QComboBox(EquipmentDialog)
        self.comboBox_type.setObjectName("comboBox_type")
        self.horizontalLayout_type.addWidget(self.comboBox_type)
        self.horizontalLayout.addLayout(self.horizontalLayout_type)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.splitter_equipment = QtWidgets.QSplitter(EquipmentDialog)
        self.splitter_equipment.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_equipment.setObjectName("splitter_equipment")
        self.label_equipment = QtWidgets.QLabel(self.splitter_equipment)
        self.label_equipment.setObjectName("label_equipment")
        self.comboBox_equipment = QtWidgets.QComboBox(self.splitter_equipment)
        self.comboBox_equipment.setObjectName("comboBox_equipment")
        self.verticalLayout.addWidget(self.splitter_equipment)
        self.splitter_enchantment = QtWidgets.QSplitter(EquipmentDialog)
        self.splitter_enchantment.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_enchantment.setObjectName("splitter_enchantment")
        self.label_enchantment = QtWidgets.QLabel(self.splitter_enchantment)
        self.label_enchantment.setObjectName("label_enchantment")
        self.comboBox_enchantment = QtWidgets.QComboBox(self.splitter_enchantment)
        self.comboBox_enchantment.setObjectName("comboBox_enchantment")
        self.verticalLayout.addWidget(self.splitter_enchantment)
        self.splitter_badge = QtWidgets.QSplitter(EquipmentDialog)
        self.splitter_badge.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_badge.setObjectName("splitter_badge")
        self.label_badge = QtWidgets.QLabel(self.splitter_badge)
        self.label_badge.setObjectName("label_badge")
        self.comboBox_badge0 = QtWidgets.QComboBox(self.splitter_badge)
        self.comboBox_badge0.setObjectName("comboBox_badge0")
        self.comboBox_badge1 = QtWidgets.QComboBox(self.splitter_badge)
        self.comboBox_badge1.setObjectName("comboBox_badge1")
        self.verticalLayout.addWidget(self.splitter_badge)
        self.horizontalLayout_strengthen = QtWidgets.QHBoxLayout()
        self.horizontalLayout_strengthen.setObjectName("horizontalLayout_strengthen")
        self.comboBox_strengthenType = QtWidgets.QComboBox(EquipmentDialog)
        self.comboBox_strengthenType.setObjectName("comboBox_strengthenType")
        self.comboBox_strengthenType.addItem("")
        self.comboBox_strengthenType.addItem("")
        self.horizontalLayout_strengthen.addWidget(self.comboBox_strengthenType)
        self.comboBox_strengthenLevel = QtWidgets.QComboBox(EquipmentDialog)
        self.comboBox_strengthenLevel.setObjectName("comboBox_strengthenLevel")
        self.horizontalLayout_strengthen.addWidget(self.comboBox_strengthenLevel)
        self.verticalLayout.addLayout(self.horizontalLayout_strengthen)
        self.scrollArea = QtWidgets.QScrollArea(EquipmentDialog)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 404, 150))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.textBrowser = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout.addWidget(self.textBrowser, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.buttonBox = QtWidgets.QDialogButtonBox(EquipmentDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(EquipmentDialog)
        self.buttonBox.accepted.connect(EquipmentDialog.accept)
        self.buttonBox.rejected.connect(EquipmentDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(EquipmentDialog)

    def retranslateUi(self, EquipmentDialog):
        _translate = QtCore.QCoreApplication.translate
        EquipmentDialog.setWindowTitle(_translate("EquipmentDialog", "Dialog"))
        self.label_grade.setText(_translate("EquipmentDialog", "品级"))
        self.comboBox_grade.setItemText(0, _translate("EquipmentDialog", "史诗"))
        self.label_level.setText(_translate("EquipmentDialog", "等级"))
        self.comboBox_level.setItemText(0, _translate("EquipmentDialog", "85"))
        self.comboBox_level.setItemText(1, _translate("EquipmentDialog", "90"))
        self.comboBox_level.setItemText(2, _translate("EquipmentDialog", "95"))
        self.label_type.setText(_translate("EquipmentDialog", "类型"))
        self.label_equipment.setText(_translate("EquipmentDialog", "装备"))
        self.label_enchantment.setText(_translate("EquipmentDialog", "附魔"))
        self.label_badge.setText(_translate("EquipmentDialog", "徽章"))
        self.comboBox_strengthenType.setItemText(0, _translate("EquipmentDialog", "强化"))
        self.comboBox_strengthenType.setItemText(1, _translate("EquipmentDialog", "附魔"))

