# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindows.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(873, 749)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 861, 698))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_character = QtWidgets.QWidget(self.layoutWidget)
        self.widget_character.setMinimumSize(QtCore.QSize(859, 30))
        self.widget_character.setObjectName("widget_character")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.widget_character)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_character = QtWidgets.QLabel(self.widget_character)
        self.label_character.setAlignment(QtCore.Qt.AlignCenter)
        self.label_character.setObjectName("label_character")
        self.horizontalLayout_15.addWidget(self.label_character)
        self.cBox_character = QtWidgets.QComboBox(self.widget_character)
        self.cBox_character.setObjectName("cBox_character")
        self.horizontalLayout_15.addWidget(self.cBox_character)
        self.horizontalLayout_19.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_profession = QtWidgets.QLabel(self.widget_character)
        self.label_profession.setAlignment(QtCore.Qt.AlignCenter)
        self.label_profession.setObjectName("label_profession")
        self.horizontalLayout_16.addWidget(self.label_profession)
        self.cbox_profession = QtWidgets.QComboBox(self.widget_character)
        self.cbox_profession.setObjectName("cbox_profession")
        self.horizontalLayout_16.addWidget(self.cbox_profession)
        self.horizontalLayout_19.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_level = QtWidgets.QLabel(self.widget_character)
        self.label_level.setAlignment(QtCore.Qt.AlignCenter)
        self.label_level.setObjectName("label_level")
        self.horizontalLayout_17.addWidget(self.label_level)
        self.cbox_level = QtWidgets.QComboBox(self.widget_character)
        self.cbox_level.setObjectName("cbox_level")
        self.horizontalLayout_17.addWidget(self.cbox_level)
        self.horizontalLayout_19.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.buttom_start = QtWidgets.QPushButton(self.widget_character)
        self.buttom_start.setObjectName("buttom_start")
        self.horizontalLayout_18.addWidget(self.buttom_start)
        self.buttom_reset = QtWidgets.QPushButton(self.widget_character)
        self.buttom_reset.setObjectName("buttom_reset")
        self.horizontalLayout_18.addWidget(self.buttom_reset)
        self.horizontalLayout_19.addLayout(self.horizontalLayout_18)
        self.verticalLayout.addWidget(self.widget_character)
        self.tabWidget_character = QtWidgets.QTabWidget(self.layoutWidget)
        self.tabWidget_character.setMinimumSize(QtCore.QSize(859, 637))
        self.tabWidget_character.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabWidget_character.setObjectName("tabWidget_character")
        self.tabWidget_character_page_equipment = QtWidgets.QWidget()
        self.tabWidget_character_page_equipment.setToolTipDuration(1)
        self.tabWidget_character_page_equipment.setObjectName("tabWidget_character_page_equipment")
        self.tabWidget_equipment = QtWidgets.QTabWidget(self.tabWidget_character_page_equipment)
        self.tabWidget_equipment.setGeometry(QtCore.QRect(11, 11, 381, 301))
        self.tabWidget_equipment.setObjectName("tabWidget_equipment")
        self.tabWidget_equipment_page_equipment = QtWidgets.QWidget()
        self.tabWidget_equipment_page_equipment.setObjectName("tabWidget_equipment_page_equipment")
        self.equipment_coat = QtWidgets.QPushButton(self.tabWidget_equipment_page_equipment)
        self.equipment_coat.setGeometry(QtCore.QRect(80, 30, 51, 51))
        self.equipment_coat.setObjectName("equipment_coat")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.equipment_coat)
        self.equipment_earring = QtWidgets.QPushButton(self.tabWidget_equipment_page_equipment)
        self.equipment_earring.setGeometry(QtCore.QRect(240, 210, 51, 51))
        self.equipment_earring.setObjectName("equipment_earring")
        self.buttonGroup.addButton(self.equipment_earring)
        self.equipment_necklace = QtWidgets.QPushButton(self.tabWidget_equipment_page_equipment)
        self.equipment_necklace.setGeometry(QtCore.QRect(300, 90, 51, 51))
        self.equipment_necklace.setObjectName("equipment_necklace")
        self.buttonGroup.addButton(self.equipment_necklace)
        self.equipment_shoulder = QtWidgets.QPushButton(self.tabWidget_equipment_page_equipment)
        self.equipment_shoulder.setGeometry(QtCore.QRect(20, 30, 51, 51))
        self.equipment_shoulder.setObjectName("equipment_shoulder")
        self.buttonGroup.addButton(self.equipment_shoulder)
        self.equipment_belt = QtWidgets.QPushButton(self.tabWidget_equipment_page_equipment)
        self.equipment_belt.setGeometry(QtCore.QRect(80, 90, 51, 51))
        self.equipment_belt.setObjectName("equipment_belt")
        self.buttonGroup.addButton(self.equipment_belt)
        self.equipment_weapon = QtWidgets.QPushButton(self.tabWidget_equipment_page_equipment)
        self.equipment_weapon.setGeometry(QtCore.QRect(240, 30, 51, 51))
        self.equipment_weapon.setObjectName("equipment_weapon")
        self.buttonGroup.addButton(self.equipment_weapon)
        self.equipment_rings = QtWidgets.QPushButton(self.tabWidget_equipment_page_equipment)
        self.equipment_rings.setGeometry(QtCore.QRect(300, 150, 51, 51))
        self.equipment_rings.setObjectName("equipment_rings")
        self.buttonGroup.addButton(self.equipment_rings)
        self.equipment_pants = QtWidgets.QPushButton(self.tabWidget_equipment_page_equipment)
        self.equipment_pants.setGeometry(QtCore.QRect(20, 90, 51, 51))
        self.equipment_pants.setObjectName("equipment_pants")
        self.buttonGroup.addButton(self.equipment_pants)
        self.equipment_shoes = QtWidgets.QPushButton(self.tabWidget_equipment_page_equipment)
        self.equipment_shoes.setGeometry(QtCore.QRect(20, 150, 51, 51))
        self.equipment_shoes.setObjectName("equipment_shoes")
        self.buttonGroup.addButton(self.equipment_shoes)
        self.equipment_magicShone = QtWidgets.QPushButton(self.tabWidget_equipment_page_equipment)
        self.equipment_magicShone.setGeometry(QtCore.QRect(300, 210, 51, 51))
        self.equipment_magicShone.setObjectName("equipment_magicShone")
        self.buttonGroup.addButton(self.equipment_magicShone)
        self.equipment_aider = QtWidgets.QPushButton(self.tabWidget_equipment_page_equipment)
        self.equipment_aider.setGeometry(QtCore.QRect(240, 150, 51, 51))
        self.equipment_aider.setObjectName("equipment_aider")
        self.buttonGroup.addButton(self.equipment_aider)
        self.equipment_bracelet = QtWidgets.QPushButton(self.tabWidget_equipment_page_equipment)
        self.equipment_bracelet.setGeometry(QtCore.QRect(240, 90, 51, 51))
        self.equipment_bracelet.setObjectName("equipment_bracelet")
        self.buttonGroup.addButton(self.equipment_bracelet)
        self.equipment_title = QtWidgets.QPushButton(self.tabWidget_equipment_page_equipment)
        self.equipment_title.setGeometry(QtCore.QRect(300, 30, 51, 51))
        self.equipment_title.setObjectName("equipment_title")
        self.buttonGroup.addButton(self.equipment_title)
        self.tabWidget_equipment.addTab(self.tabWidget_equipment_page_equipment, "")
        self.tabWidget_equipment_page_fashion = QtWidgets.QWidget()
        self.tabWidget_equipment_page_fashion.setObjectName("tabWidget_equipment_page_fashion")
        self.fashion_hat = QtWidgets.QPushButton(self.tabWidget_equipment_page_fashion)
        self.fashion_hat.setGeometry(QtCore.QRect(160, 40, 51, 51))
        self.fashion_hat.setText("")
        self.fashion_hat.setObjectName("fashion_hat")
        self.fashion_hair = QtWidgets.QPushButton(self.tabWidget_equipment_page_fashion)
        self.fashion_hair.setGeometry(QtCore.QRect(220, 40, 51, 51))
        self.fashion_hair.setText("")
        self.fashion_hair.setObjectName("fashion_hair")
        self.fashion_facialDecoration = QtWidgets.QPushButton(self.tabWidget_equipment_page_fashion)
        self.fashion_facialDecoration.setGeometry(QtCore.QRect(280, 40, 51, 51))
        self.fashion_facialDecoration.setText("")
        self.fashion_facialDecoration.setObjectName("fashion_facialDecoration")
        self.pushButton_19 = QtWidgets.QPushButton(self.tabWidget_equipment_page_fashion)
        self.pushButton_19.setGeometry(QtCore.QRect(160, 100, 51, 51))
        self.pushButton_19.setText("")
        self.pushButton_19.setObjectName("pushButton_19")
        self.fashion_coat = QtWidgets.QPushButton(self.tabWidget_equipment_page_fashion)
        self.fashion_coat.setGeometry(QtCore.QRect(220, 100, 51, 51))
        self.fashion_coat.setText("")
        self.fashion_coat.setObjectName("fashion_coat")
        self.pushButton_21 = QtWidgets.QPushButton(self.tabWidget_equipment_page_fashion)
        self.pushButton_21.setGeometry(QtCore.QRect(280, 100, 51, 51))
        self.pushButton_21.setText("")
        self.pushButton_21.setObjectName("pushButton_21")
        self.pushButton_22 = QtWidgets.QPushButton(self.tabWidget_equipment_page_fashion)
        self.pushButton_22.setGeometry(QtCore.QRect(160, 160, 51, 51))
        self.pushButton_22.setText("")
        self.pushButton_22.setObjectName("pushButton_22")
        self.fashion_pants = QtWidgets.QPushButton(self.tabWidget_equipment_page_fashion)
        self.fashion_pants.setGeometry(QtCore.QRect(220, 160, 51, 51))
        self.fashion_pants.setText("")
        self.fashion_pants.setObjectName("fashion_pants")
        self.fashion_shoes = QtWidgets.QPushButton(self.tabWidget_equipment_page_fashion)
        self.fashion_shoes.setGeometry(QtCore.QRect(280, 160, 51, 51))
        self.fashion_shoes.setText("")
        self.fashion_shoes.setObjectName("fashion_shoes")
        self.fashion_halo = QtWidgets.QPushButton(self.tabWidget_equipment_page_fashion)
        self.fashion_halo.setGeometry(QtCore.QRect(90, 100, 51, 51))
        self.fashion_halo.setText("")
        self.fashion_halo.setObjectName("fashion_halo")
        self.fashion_weapon = QtWidgets.QPushButton(self.tabWidget_equipment_page_fashion)
        self.fashion_weapon.setGeometry(QtCore.QRect(90, 40, 51, 51))
        self.fashion_weapon.setText("")
        self.fashion_weapon.setObjectName("fashion_weapon")
        self.tabWidget_equipment.addTab(self.tabWidget_equipment_page_fashion, "")
        self.tabWidget_equipment_tab_pet = QtWidgets.QWidget()
        self.tabWidget_equipment_tab_pet.setObjectName("tabWidget_equipment_tab_pet")
        self.pet_pet = QtWidgets.QPushButton(self.tabWidget_equipment_tab_pet)
        self.pet_pet.setGeometry(QtCore.QRect(70, 30, 51, 51))
        self.pet_pet.setText("")
        self.pet_pet.setObjectName("pet_pet")
        self.pet_red = QtWidgets.QPushButton(self.tabWidget_equipment_tab_pet)
        self.pet_red.setGeometry(QtCore.QRect(250, 30, 51, 51))
        self.pet_red.setText("")
        self.pet_red.setObjectName("pet_red")
        self.pet_green = QtWidgets.QPushButton(self.tabWidget_equipment_tab_pet)
        self.pet_green.setGeometry(QtCore.QRect(250, 90, 51, 51))
        self.pet_green.setText("")
        self.pet_green.setObjectName("pet_green")
        self.pet_blue = QtWidgets.QPushButton(self.tabWidget_equipment_tab_pet)
        self.pet_blue.setGeometry(QtCore.QRect(250, 150, 51, 51))
        self.pet_blue.setText("")
        self.pet_blue.setObjectName("pet_blue")
        self.tabWidget_equipment.addTab(self.tabWidget_equipment_tab_pet, "")
        self.tabWidget_equipment_tab_medel = QtWidgets.QWidget()
        self.tabWidget_equipment_tab_medel.setObjectName("tabWidget_equipment_tab_medel")
        self.medel_medel = QtWidgets.QPushButton(self.tabWidget_equipment_tab_medel)
        self.medel_medel.setGeometry(QtCore.QRect(160, 90, 51, 51))
        self.medel_medel.setText("")
        self.medel_medel.setObjectName("medel_medel")
        self.medel_TopRight = QtWidgets.QPushButton(self.tabWidget_equipment_tab_medel)
        self.medel_TopRight.setGeometry(QtCore.QRect(240, 30, 51, 51))
        self.medel_TopRight.setText("")
        self.medel_TopRight.setObjectName("medel_TopRight")
        self.medel_BottomRight = QtWidgets.QPushButton(self.tabWidget_equipment_tab_medel)
        self.medel_BottomRight.setGeometry(QtCore.QRect(240, 150, 51, 51))
        self.medel_BottomRight.setText("")
        self.medel_BottomRight.setObjectName("medel_BottomRight")
        self.medel_BottomLeft = QtWidgets.QPushButton(self.tabWidget_equipment_tab_medel)
        self.medel_BottomLeft.setGeometry(QtCore.QRect(80, 150, 51, 51))
        self.medel_BottomLeft.setText("")
        self.medel_BottomLeft.setObjectName("medel_BottomLeft")
        self.medel_TopLeft = QtWidgets.QPushButton(self.tabWidget_equipment_tab_medel)
        self.medel_TopLeft.setGeometry(QtCore.QRect(80, 30, 51, 51))
        self.medel_TopLeft.setText("")
        self.medel_TopLeft.setObjectName("medel_TopLeft")
        self.tabWidget_equipment.addTab(self.tabWidget_equipment_tab_medel, "")
        self.scrollArea = QtWidgets.QScrollArea(self.tabWidget_character_page_equipment)
        self.scrollArea.setGeometry(QtCore.QRect(10, 320, 381, 281))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -148, 358, 427))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_moveSpeed = QtWidgets.QHBoxLayout()
        self.horizontalLayout_moveSpeed.setObjectName("horizontalLayout_moveSpeed")
        self.label_attribute_moveSpeed = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_attribute_moveSpeed.setObjectName("label_attribute_moveSpeed")
        self.horizontalLayout_moveSpeed.addWidget(self.label_attribute_moveSpeed)
        self.attribute_moveSpeed = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.attribute_moveSpeed.setText("")
        self.attribute_moveSpeed.setObjectName("attribute_moveSpeed")
        self.horizontalLayout_moveSpeed.addWidget(self.attribute_moveSpeed)
        self.gridLayout.addLayout(self.horizontalLayout_moveSpeed, 8, 0, 1, 1)
        self.horizontalLayout_phyCritRate = QtWidgets.QHBoxLayout()
        self.horizontalLayout_phyCritRate.setObjectName("horizontalLayout_phyCritRate")
        self.lable_attribute_phyCritRate = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.lable_attribute_phyCritRate.setObjectName("lable_attribute_phyCritRate")
        self.horizontalLayout_phyCritRate.addWidget(self.lable_attribute_phyCritRate)
        self.attribute_phyCritRate = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.attribute_phyCritRate.setText("")
        self.attribute_phyCritRate.setObjectName("attribute_phyCritRate")
        self.horizontalLayout_phyCritRate.addWidget(self.attribute_phyCritRate)
        self.gridLayout.addLayout(self.horizontalLayout_phyCritRate, 6, 0, 1, 1)
        self.horizontalLayout_fireStrengthening = QtWidgets.QHBoxLayout()
        self.horizontalLayout_fireStrengthening.setObjectName("horizontalLayout_fireStrengthening")
        self.label_attribute_fireStrengthening = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_attribute_fireStrengthening.setObjectName("label_attribute_fireStrengthening")
        self.horizontalLayout_fireStrengthening.addWidget(self.label_attribute_fireStrengthening)
        self.attribute_fireStrengthening = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.attribute_fireStrengthening.setText("")
        self.attribute_fireStrengthening.setObjectName("attribute_fireStrengthening")
        self.horizontalLayout_fireStrengthening.addWidget(self.attribute_fireStrengthening)
        self.gridLayout.addLayout(self.horizontalLayout_fireStrengthening, 12, 0, 1, 1)
        self.horizontalLayout_fireResistance = QtWidgets.QHBoxLayout()
        self.horizontalLayout_fireResistance.setObjectName("horizontalLayout_fireResistance")
        self.label_attribute_fireResistance = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_attribute_fireResistance.setObjectName("label_attribute_fireResistance")
        self.horizontalLayout_fireResistance.addWidget(self.label_attribute_fireResistance)
        self.attribute_fireResistance = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.attribute_fireResistance.setText("")
        self.attribute_fireResistance.setObjectName("attribute_fireResistance")
        self.horizontalLayout_fireResistance.addWidget(self.attribute_fireResistance)
        self.gridLayout.addLayout(self.horizontalLayout_fireResistance, 12, 1, 1, 1)
        self.horizontalLayout_attackSpeed = QtWidgets.QHBoxLayout()
        self.horizontalLayout_attackSpeed.setObjectName("horizontalLayout_attackSpeed")
        self.label_attribute_attackSpeed = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_attribute_attackSpeed.setObjectName("label_attribute_attackSpeed")
        self.horizontalLayout_attackSpeed.addWidget(self.label_attribute_attackSpeed)
        self.attribute_attackSpeed = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.attribute_attackSpeed.setText("")
        self.attribute_attackSpeed.setObjectName("attribute_attackSpeed")
        self.horizontalLayout_attackSpeed.addWidget(self.attribute_attackSpeed)
        self.gridLayout.addLayout(self.horizontalLayout_attackSpeed, 7, 0, 1, 1)
        self.horizontalLayout_lightStrengthening = QtWidgets.QHBoxLayout()
        self.horizontalLayout_lightStrengthening.setObjectName("horizontalLayout_lightStrengthening")
        self.label_attribute_lightStrengthening = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_attribute_lightStrengthening.setObjectName("label_attribute_lightStrengthening")
        self.horizontalLayout_lightStrengthening.addWidget(self.label_attribute_lightStrengthening)
        self.attribute_lightStrengthening = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.attribute_lightStrengthening.setText("")
        self.attribute_lightStrengthening.setObjectName("attribute_lightStrengthening")
        self.horizontalLayout_lightStrengthening.addWidget(self.attribute_lightStrengthening)
        self.gridLayout.addLayout(self.horizontalLayout_lightStrengthening, 14, 0, 1, 1)
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.label_attribute_lightResistance = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_attribute_lightResistance.setObjectName("label_attribute_lightResistance")
        self.horizontalLayout_34.addWidget(self.label_attribute_lightResistance)
        self.attribute_lightResistance = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.attribute_lightResistance.setText("")
        self.attribute_lightResistance.setObjectName("attribute_lightResistance")
        self.horizontalLayout_34.addWidget(self.attribute_lightResistance)
        self.gridLayout.addLayout(self.horizontalLayout_34, 14, 1, 1, 1)
        self.horizontalLayout_stiff = QtWidgets.QHBoxLayout()
        self.horizontalLayout_stiff.setObjectName("horizontalLayout_stiff")
        self.label_attribute_stiff = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_attribute_stiff.setObjectName("label_attribute_stiff")
        self.horizontalLayout_stiff.addWidget(self.label_attribute_stiff)
        self.attribute_stiff = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.attribute_stiff.setText("")
        self.attribute_stiff.setObjectName("attribute_stiff")
        self.horizontalLayout_stiff.addWidget(self.attribute_stiff)
        self.gridLayout.addLayout(self.horizontalLayout_stiff, 11, 0, 1, 1)
        self.horizontalLayout_magicDefense = QtWidgets.QHBoxLayout()
        self.horizontalLayout_magicDefense.setObjectName("horizontalLayout_magicDefense")
        self.label_attribute_magicDefense = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_attribute_magicDefense.setObjectName("label_attribute_magicDefense")
        self.horizontalLayout_magicDefense.addWidget(self.label_attribute_magicDefense)
        self.attribute_magicDefense = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.attribute_magicDefense.setText("")
        self.attribute_magicDefense.setObjectName("attribute_magicDefense")
        self.horizontalLayout_magicDefense.addWidget(self.attribute_magicDefense)
        self.gridLayout.addLayout(self.horizontalLayout_magicDefense, 5, 1, 1, 1)
        self.horizontalLayout_mpRecovery = QtWidgets.QHBoxLayout()
        self.horizontalLayout_mpRecovery.setObjectName("horizontalLayout_mpRecovery")
        self.label_attribute_mpRecovery = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_attribute_mpRecovery.setObjectName("label_attribute_mpRecovery")
        self.horizontalLayout_mpRecovery.addWidget(self.label_attribute_mpRecovery)
        self.attribute_mpRecovery = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.attribute_mpRecovery.setText("")
        self.attribute_mpRecovery.setObjectName("attribute_mpRecovery")
        self.horizontalLayout_mpRecovery.addWidget(self.attribute_mpRecovery)
        self.gridLayout.addLayout(self.horizontalLayout_mpRecovery, 10, 1, 1, 1)
        self.horizontalLayout_iceStrengthening = QtWidgets.QHBoxLayout()
        self.horizontalLayout_iceStrengthening.setObjectName("horizontalLayout_iceStrengthening")
        self.label_attribute_iceStrengthening = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_attribute_iceStrengthening.setObjectName("label_attribute_iceStrengthening")
        self.horizontalLayout_iceStrengthening.addWidget(self.label_attribute_iceStrengthening)
        self.attribute_iceStrengthening = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.attribute_iceStrengthening.setText("")
        self.attribute_iceStrengthening.setObjectName("attribute_iceStrengthening")
        self.horizontalLayout_iceStrengthening.addWidget(self.attribute_iceStrengthening)
        self.gridLayout.addLayout(self.horizontalLayout_iceStrengthening, 13, 0, 1, 1)
        self.horizontalLayout_antiEvil = QtWidgets.QHBoxLayout()
        self.horizontalLayout_antiEvil.setObjectName("horizontalLayout_antiEvil")
        self.label_attribute_antiEvil = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_attribute_antiEvil.setObjectName("label_attribute_antiEvil")
        self.horizontalLayout_antiEvil.addWidget(self.label_attribute_antiEvil)
        self.attribute_antiEvil = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.attribute_antiEvil.setText("")
        self.attribute_antiEvil.setObjectName("attribute_antiEvil")
        self.horizontalLayout_antiEvil.addWidget(self.attribute_antiEvil)
        self.gridLayout.addLayout(self.horizontalLayout_antiEvil, 8, 1, 1, 1)
        self.horizontalLayout_hpRecovery = QtWidgets.QHBoxLayout()
        self.horizontalLayout_hpRecovery.setObjectName("horizontalLayout_hpRecovery")
        self.label_attribute_hpRecovery = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_attribute_hpRecovery.setObjectName("label_attribute_hpRecovery")
        self.horizontalLayout_hpRecovery.addWidget(self.label_attribute_hpRecovery)
        self.attribute_hpRecovery = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.attribute_hpRecovery.setText("")
        self.attribute_hpRecovery.setObjectName("attribute_hpRecovery")
        self.horizontalLayout_hpRecovery.addWidget(self.attribute_hpRecovery)
        self.gridLayout.addLayout(self.horizontalLayout_hpRecovery, 10, 0, 1, 1)
        self.horizontalLayout_singingSpeed = QtWidgets.QHBoxLayout()
        self.horizontalLayout_singingSpeed.setObjectName("horizontalLayout_singingSpeed")
        self.label_attribute_singingSpeed = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_attribute_singingSpeed.setObjectName("label_attribute_singingSpeed")
        self.horizontalLayout_singingSpeed.addWidget(self.label_attribute_singingSpeed)
        self.attribute_singingSpeed = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.attribute_singingSpeed.setText("")
        self.attribute_singingSpeed.setObjectName("attribute_singingSpeed")
        self.horizontalLayout_singingSpeed.addWidget(self.attribute_singingSpeed)
        self.gridLayout.addLayout(self.horizontalLayout_singingSpeed, 7, 1, 1, 1)
        self.horizontalLayout_hitRate = QtWidgets.QHBoxLayout()
        self.horizontalLayout_hitRate.setObjectName("horizontalLayout_hitRate")
        self.label_attribute_hitRate = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_attribute_hitRate.setObjectName("label_attribute_hitRate")
        self.horizontalLayout_hitRate.addWidget(self.label_attribute_hitRate)
        self.attribute_hitRate = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.attribute_hitRate.setText("")
        self.attribute_hitRate.setObjectName("attribute_hitRate")
        self.horizontalLayout_hitRate.addWidget(self.attribute_hitRate)
        self.gridLayout.addLayout(self.horizontalLayout_hitRate, 9, 0, 1, 1)
        self.horizontalLayout_dodgeRate = QtWidgets.QHBoxLayout()
        self.horizontalLayout_dodgeRate.setObjectName("horizontalLayout_dodgeRate")
        self.label_attribute_dodgeRate = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_attribute_dodgeRate.setObjectName("label_attribute_dodgeRate")
        self.horizontalLayout_dodgeRate.addWidget(self.label_attribute_dodgeRate)
        self.attribute_dodgeRage = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.attribute_dodgeRage.setText("")
        self.attribute_dodgeRage.setObjectName("attribute_dodgeRage")
        self.horizontalLayout_dodgeRate.addWidget(self.attribute_dodgeRage)
        self.gridLayout.addLayout(self.horizontalLayout_dodgeRate, 9, 1, 1, 1)
        self.horizontalLayout_iceResistance = QtWidgets.QHBoxLayout()
        self.horizontalLayout_iceResistance.setObjectName("horizontalLayout_iceResistance")
        self.label_attribute_iceResistance = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_attribute_iceResistance.setObjectName("label_attribute_iceResistance")
        self.horizontalLayout_iceResistance.addWidget(self.label_attribute_iceResistance)
        self.attribute_iceResistance = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.attribute_iceResistance.setText("")
        self.attribute_iceResistance.setObjectName("attribute_iceResistance")
        self.horizontalLayout_iceResistance.addWidget(self.attribute_iceResistance)
        self.gridLayout.addLayout(self.horizontalLayout_iceResistance, 13, 1, 1, 1)
        self.horizontalLayout_magicCritRate = QtWidgets.QHBoxLayout()
        self.horizontalLayout_magicCritRate.setObjectName("horizontalLayout_magicCritRate")
        self.label_attribute_magicCritRate = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_attribute_magicCritRate.setObjectName("label_attribute_magicCritRate")
        self.horizontalLayout_magicCritRate.addWidget(self.label_attribute_magicCritRate)
        self.attribute_magicCritRate = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.attribute_magicCritRate.setText("")
        self.attribute_magicCritRate.setObjectName("attribute_magicCritRate")
        self.horizontalLayout_magicCritRate.addWidget(self.attribute_magicCritRate)
        self.gridLayout.addLayout(self.horizontalLayout_magicCritRate, 6, 1, 1, 1)
        self.horizontalLayout_stiffness = QtWidgets.QHBoxLayout()
        self.horizontalLayout_stiffness.setObjectName("horizontalLayout_stiffness")
        self.label_attribute_stiffness = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_attribute_stiffness.setObjectName("label_attribute_stiffness")
        self.horizontalLayout_stiffness.addWidget(self.label_attribute_stiffness)
        self.attribute_stiffness = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.attribute_stiffness.setText("")
        self.attribute_stiffness.setObjectName("attribute_stiffness")
        self.horizontalLayout_stiffness.addWidget(self.attribute_stiffness)
        self.gridLayout.addLayout(self.horizontalLayout_stiffness, 11, 1, 1, 1)
        self.horizontalLayout_independentAttack = QtWidgets.QHBoxLayout()
        self.horizontalLayout_independentAttack.setObjectName("horizontalLayout_independentAttack")
        self.label_attritube_independentAttack = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_attritube_independentAttack.setObjectName("label_attritube_independentAttack")
        self.horizontalLayout_independentAttack.addWidget(self.label_attritube_independentAttack)
        self.attritube_independentAttack = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.attritube_independentAttack.setText("")
        self.attritube_independentAttack.setObjectName("attritube_independentAttack")
        self.horizontalLayout_independentAttack.addWidget(self.attritube_independentAttack)
        self.gridLayout.addLayout(self.horizontalLayout_independentAttack, 4, 0, 1, 2)
        self.horizontalLayout_strength = QtWidgets.QHBoxLayout()
        self.horizontalLayout_strength.setObjectName("horizontalLayout_strength")
        self.label_attribute_strength = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_attribute_strength.setObjectName("label_attribute_strength")
        self.horizontalLayout_strength.addWidget(self.label_attribute_strength)
        self.attribute_strength = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.attribute_strength.setText("")
        self.attribute_strength.setObjectName("attribute_strength")
        self.horizontalLayout_strength.addWidget(self.attribute_strength)
        self.gridLayout.addLayout(self.horizontalLayout_strength, 1, 0, 1, 1)
        self.horizontalLayout_intelligence = QtWidgets.QHBoxLayout()
        self.horizontalLayout_intelligence.setObjectName("horizontalLayout_intelligence")
        self.label_attribute_intelligence = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_attribute_intelligence.setObjectName("label_attribute_intelligence")
        self.horizontalLayout_intelligence.addWidget(self.label_attribute_intelligence)
        self.attribute_intelligence = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.attribute_intelligence.setText("")
        self.attribute_intelligence.setObjectName("attribute_intelligence")
        self.horizontalLayout_intelligence.addWidget(self.attribute_intelligence)
        self.gridLayout.addLayout(self.horizontalLayout_intelligence, 1, 1, 1, 1)
        self.horizontalLayout_mp = QtWidgets.QHBoxLayout()
        self.horizontalLayout_mp.setObjectName("horizontalLayout_mp")
        self.label_attribute_mp = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_attribute_mp.setObjectName("label_attribute_mp")
        self.horizontalLayout_mp.addWidget(self.label_attribute_mp)
        self.attribute_mp = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.attribute_mp.setText("")
        self.attribute_mp.setObjectName("attribute_mp")
        self.horizontalLayout_mp.addWidget(self.attribute_mp)
        self.gridLayout.addLayout(self.horizontalLayout_mp, 0, 1, 1, 1)
        self.horizontalLayout_spirit = QtWidgets.QHBoxLayout()
        self.horizontalLayout_spirit.setObjectName("horizontalLayout_spirit")
        self.label_attribute_spirit = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_attribute_spirit.setObjectName("label_attribute_spirit")
        self.horizontalLayout_spirit.addWidget(self.label_attribute_spirit)
        self.attribute_spirit = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.attribute_spirit.setText("")
        self.attribute_spirit.setObjectName("attribute_spirit")
        self.horizontalLayout_spirit.addWidget(self.attribute_spirit)
        self.gridLayout.addLayout(self.horizontalLayout_spirit, 2, 1, 1, 1)
        self.horizontalLayout_phyAttack = QtWidgets.QHBoxLayout()
        self.horizontalLayout_phyAttack.setSpacing(7)
        self.horizontalLayout_phyAttack.setObjectName("horizontalLayout_phyAttack")
        self.label_attribute_phyAttack = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_attribute_phyAttack.setObjectName("label_attribute_phyAttack")
        self.horizontalLayout_phyAttack.addWidget(self.label_attribute_phyAttack)
        self.attribute_phyAttack = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.attribute_phyAttack.setText("")
        self.attribute_phyAttack.setObjectName("attribute_phyAttack")
        self.horizontalLayout_phyAttack.addWidget(self.attribute_phyAttack)
        self.gridLayout.addLayout(self.horizontalLayout_phyAttack, 3, 0, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_attribute_magicAttack = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_attribute_magicAttack.setObjectName("label_attribute_magicAttack")
        self.horizontalLayout_10.addWidget(self.label_attribute_magicAttack)
        self.attribute_magicAttack = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.attribute_magicAttack.setText("")
        self.attribute_magicAttack.setObjectName("attribute_magicAttack")
        self.horizontalLayout_10.addWidget(self.attribute_magicAttack)
        self.gridLayout.addLayout(self.horizontalLayout_10, 3, 1, 1, 1)
        self.horizontalLayout_hp = QtWidgets.QHBoxLayout()
        self.horizontalLayout_hp.setObjectName("horizontalLayout_hp")
        self.label_attribute_hp = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_attribute_hp.setObjectName("label_attribute_hp")
        self.horizontalLayout_hp.addWidget(self.label_attribute_hp)
        self.attribute_hp = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.attribute_hp.setText("")
        self.attribute_hp.setObjectName("attribute_hp")
        self.horizontalLayout_hp.addWidget(self.attribute_hp)
        self.gridLayout.addLayout(self.horizontalLayout_hp, 0, 0, 1, 1)
        self.horizontalLayout_phyDefense = QtWidgets.QHBoxLayout()
        self.horizontalLayout_phyDefense.setObjectName("horizontalLayout_phyDefense")
        self.label_attribute_phyDefense = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_attribute_phyDefense.setObjectName("label_attribute_phyDefense")
        self.horizontalLayout_phyDefense.addWidget(self.label_attribute_phyDefense)
        self.attribute_phyDefense = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.attribute_phyDefense.setText("")
        self.attribute_phyDefense.setObjectName("attribute_phyDefense")
        self.horizontalLayout_phyDefense.addWidget(self.attribute_phyDefense)
        self.gridLayout.addLayout(self.horizontalLayout_phyDefense, 5, 0, 1, 1)
        self.horizontalLayout_stamina = QtWidgets.QHBoxLayout()
        self.horizontalLayout_stamina.setObjectName("horizontalLayout_stamina")
        self.label_attribute_stamina = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_attribute_stamina.setObjectName("label_attribute_stamina")
        self.horizontalLayout_stamina.addWidget(self.label_attribute_stamina)
        self.attribute_stamina = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.attribute_stamina.setText("")
        self.attribute_stamina.setObjectName("attribute_stamina")
        self.horizontalLayout_stamina.addWidget(self.attribute_stamina)
        self.gridLayout.addLayout(self.horizontalLayout_stamina, 2, 0, 1, 1)
        self.horizontalLayout_darkResistance = QtWidgets.QHBoxLayout()
        self.horizontalLayout_darkResistance.setObjectName("horizontalLayout_darkResistance")
        self.label_attribute_darkResistance = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_attribute_darkResistance.setObjectName("label_attribute_darkResistance")
        self.horizontalLayout_darkResistance.addWidget(self.label_attribute_darkResistance)
        self.aattribute_darkResistance = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.aattribute_darkResistance.setText("")
        self.aattribute_darkResistance.setObjectName("aattribute_darkResistance")
        self.horizontalLayout_darkResistance.addWidget(self.aattribute_darkResistance)
        self.gridLayout.addLayout(self.horizontalLayout_darkResistance, 15, 1, 1, 1)
        self.horizontalLayout_darkStrengthening = QtWidgets.QHBoxLayout()
        self.horizontalLayout_darkStrengthening.setObjectName("horizontalLayout_darkStrengthening")
        self.label_attribute_darkStrengthening = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_attribute_darkStrengthening.setObjectName("label_attribute_darkStrengthening")
        self.horizontalLayout_darkStrengthening.addWidget(self.label_attribute_darkStrengthening)
        self.attribute_darkStrengthening = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.attribute_darkStrengthening.setText("")
        self.attribute_darkStrengthening.setObjectName("attribute_darkStrengthening")
        self.horizontalLayout_darkStrengthening.addWidget(self.attribute_darkStrengthening)
        self.gridLayout.addLayout(self.horizontalLayout_darkStrengthening, 15, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.tabWidget_character.addTab(self.tabWidget_character_page_equipment, "")
        self.tabWidget_character_page_skill = QtWidgets.QWidget()
        self.tabWidget_character_page_skill.setObjectName("tabWidget_character_page_skill")
        self.tabWidget_character.addTab(self.tabWidget_character_page_skill, "")
        self.tabWidget_character_page_damage = QtWidgets.QWidget()
        self.tabWidget_character_page_damage.setObjectName("tabWidget_character_page_damage")
        self.tabWidget_character.addTab(self.tabWidget_character_page_damage, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget_character.addTab(self.tab_4, "")
        self.verticalLayout.addWidget(self.tabWidget_character)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 873, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_open = QtWidgets.QAction(MainWindow)
        self.action_open.setObjectName("action_open")
        self.action_save = QtWidgets.QAction(MainWindow)
        self.action_save.setObjectName("action_save")
        self.action_save_as = QtWidgets.QAction(MainWindow)
        self.action_save_as.setObjectName("action_save_as")
        self.actionquit = QtWidgets.QAction(MainWindow)
        self.actionquit.setObjectName("actionquit")
        self.actionhelp = QtWidgets.QAction(MainWindow)
        self.actionhelp.setObjectName("actionhelp")
        self.actionhelo = QtWidgets.QAction(MainWindow)
        self.actionhelo.setObjectName("actionhelo")
        self.menu.addAction(self.action_open)
        self.menu.addSeparator()
        self.menu.addAction(self.action_save)
        self.menu.addAction(self.action_save_as)
        self.menu.addSeparator()
        self.menu.addAction(self.actionquit)
        self.menu_2.addAction(self.actionhelp)
        self.menu_3.addAction(self.actionhelo)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget_character.setCurrentIndex(0)
        self.tabWidget_equipment.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DNF伤害模拟器V1.0  -  by skander820"))
        self.label_character.setText(_translate("MainWindow", "角色"))
        self.label_profession.setText(_translate("MainWindow", "职业"))
        self.label_level.setText(_translate("MainWindow", "等级"))
        self.buttom_start.setText(_translate("MainWindow", "开始"))
        self.buttom_reset.setText(_translate("MainWindow", "重置"))
        self.tabWidget_equipment.setTabText(self.tabWidget_equipment.indexOf(self.tabWidget_equipment_page_equipment), _translate("MainWindow", "装备"))
        self.tabWidget_equipment.setTabText(self.tabWidget_equipment.indexOf(self.tabWidget_equipment_page_fashion), _translate("MainWindow", "时装"))
        self.tabWidget_equipment.setTabText(self.tabWidget_equipment.indexOf(self.tabWidget_equipment_tab_pet), _translate("MainWindow", "宠物"))
        self.tabWidget_equipment.setTabText(self.tabWidget_equipment.indexOf(self.tabWidget_equipment_tab_medel), _translate("MainWindow", "勋章"))
        self.label_attribute_moveSpeed.setText(_translate("MainWindow", "移动速度"))
        self.lable_attribute_phyCritRate.setText(_translate("MainWindow", "物理暴击"))
        self.label_attribute_fireStrengthening.setText(_translate("MainWindow", "火属性强化"))
        self.label_attribute_fireResistance.setText(_translate("MainWindow", "火属性抗性"))
        self.label_attribute_attackSpeed.setText(_translate("MainWindow", "攻击速度"))
        self.label_attribute_lightStrengthening.setText(_translate("MainWindow", "光属性强化"))
        self.label_attribute_lightResistance.setText(_translate("MainWindow", "光属性抗性"))
        self.label_attribute_stiff.setText(_translate("MainWindow", "僵直度"))
        self.label_attribute_magicDefense.setText(_translate("MainWindow", "魔法防御"))
        self.label_attribute_mpRecovery.setText(_translate("MainWindow", "MP恢复量"))
        self.label_attribute_iceStrengthening.setText(_translate("MainWindow", "冰属性强化"))
        self.label_attribute_antiEvil.setText(_translate("MainWindow", "抗魔"))
        self.label_attribute_hpRecovery.setText(_translate("MainWindow", "HP恢复量"))
        self.label_attribute_singingSpeed.setText(_translate("MainWindow", "释放速度"))
        self.label_attribute_hitRate.setText(_translate("MainWindow", "命中率"))
        self.label_attribute_dodgeRate.setText(_translate("MainWindow", "回避率"))
        self.label_attribute_iceResistance.setText(_translate("MainWindow", "冰属性抗性"))
        self.label_attribute_magicCritRate.setText(_translate("MainWindow", "魔法暴击"))
        self.label_attribute_stiffness.setText(_translate("MainWindow", "硬直"))
        self.label_attritube_independentAttack.setText(_translate("MainWindow", "独立攻击力(物理/魔法)"))
        self.label_attribute_strength.setText(_translate("MainWindow", "力量"))
        self.label_attribute_intelligence.setText(_translate("MainWindow", "智力"))
        self.label_attribute_mp.setText(_translate("MainWindow", "MP"))
        self.label_attribute_spirit.setText(_translate("MainWindow", "精神"))
        self.label_attribute_phyAttack.setText(_translate("MainWindow", "物理攻击"))
        self.label_attribute_magicAttack.setText(_translate("MainWindow", "魔法攻击"))
        self.label_attribute_hp.setText(_translate("MainWindow", "HP"))
        self.label_attribute_phyDefense.setText(_translate("MainWindow", "物理防御"))
        self.label_attribute_stamina.setText(_translate("MainWindow", "体力"))
        self.label_attribute_darkResistance.setText(_translate("MainWindow", "暗属性抗性"))
        self.label_attribute_darkStrengthening.setText(_translate("MainWindow", "暗属性强化"))
        self.tabWidget_character.setTabText(self.tabWidget_character.indexOf(self.tabWidget_character_page_equipment), _translate("MainWindow", "装备"))
        self.tabWidget_character.setTabText(self.tabWidget_character.indexOf(self.tabWidget_character_page_skill), _translate("MainWindow", "技能"))
        self.tabWidget_character.setTabText(self.tabWidget_character.indexOf(self.tabWidget_character_page_damage), _translate("MainWindow", "伤害"))
        self.tabWidget_character.setTabText(self.tabWidget_character.indexOf(self.tab_4), _translate("MainWindow", "Page"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.menu_2.setTitle(_translate("MainWindow", "工具"))
        self.menu_3.setTitle(_translate("MainWindow", "帮助"))
        self.action_open.setText(_translate("MainWindow", "打开"))
        self.action_save.setText(_translate("MainWindow", "保存"))
        self.action_save_as.setText(_translate("MainWindow", "另存为"))
        self.actionquit.setText(_translate("MainWindow", "quit"))
        self.actionhelp.setText(_translate("MainWindow", "help"))
        self.actionhelo.setText(_translate("MainWindow", "help"))

