# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Role.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Role(object):
    def setupUi(self, Role):
        Role.setObjectName("Role")
        Role.resize(626, 575)
        Role.setMinimumSize(QtCore.QSize(626, 575))
        self.gridLayout_2 = QtWidgets.QGridLayout(Role)
        self.gridLayout_2.setContentsMargins(3, 3, 3, 3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget_character = QtWidgets.QWidget(Role)
        self.widget_character.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_character.setObjectName("widget_character")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_character)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_character = QtWidgets.QHBoxLayout()
        self.horizontalLayout_character.setObjectName("horizontalLayout_character")
        self.label_character = QtWidgets.QLabel(self.widget_character)
        self.label_character.setAlignment(QtCore.Qt.AlignCenter)
        self.label_character.setObjectName("label_character")
        self.horizontalLayout_character.addWidget(self.label_character)
        self.cBox_character = QtWidgets.QComboBox(self.widget_character)
        self.cBox_character.setObjectName("cBox_character")
        self.cBox_character.addItem("")
        self.cBox_character.addItem("")
        self.cBox_character.addItem("")
        self.cBox_character.addItem("")
        self.cBox_character.addItem("")
        self.cBox_character.addItem("")
        self.cBox_character.addItem("")
        self.cBox_character.addItem("")
        self.cBox_character.addItem("")
        self.cBox_character.addItem("")
        self.cBox_character.addItem("")
        self.cBox_character.addItem("")
        self.cBox_character.addItem("")
        self.cBox_character.addItem("")
        self.cBox_character.addItem("")
        self.horizontalLayout_character.addWidget(self.cBox_character)
        self.horizontalLayout.addLayout(self.horizontalLayout_character)
        self.horizontalLayout_profession = QtWidgets.QHBoxLayout()
        self.horizontalLayout_profession.setObjectName("horizontalLayout_profession")
        self.label_profession = QtWidgets.QLabel(self.widget_character)
        self.label_profession.setAlignment(QtCore.Qt.AlignCenter)
        self.label_profession.setObjectName("label_profession")
        self.horizontalLayout_profession.addWidget(self.label_profession)
        self.cbox_profession = QtWidgets.QComboBox(self.widget_character)
        self.cbox_profession.setObjectName("cbox_profession")
        self.horizontalLayout_profession.addWidget(self.cbox_profession)
        self.horizontalLayout.addLayout(self.horizontalLayout_profession)
        self.horizontalLayout_level = QtWidgets.QHBoxLayout()
        self.horizontalLayout_level.setObjectName("horizontalLayout_level")
        self.label_level = QtWidgets.QLabel(self.widget_character)
        self.label_level.setAlignment(QtCore.Qt.AlignCenter)
        self.label_level.setObjectName("label_level")
        self.horizontalLayout_level.addWidget(self.label_level)
        self.cbox_level = QtWidgets.QComboBox(self.widget_character)
        self.cbox_level.setObjectName("cbox_level")
        self.cbox_level.addItem("")
        self.cbox_level.addItem("")
        self.horizontalLayout_level.addWidget(self.cbox_level)
        self.horizontalLayout.addLayout(self.horizontalLayout_level)
        self.horizontalLayout_startReset = QtWidgets.QHBoxLayout()
        self.horizontalLayout_startReset.setObjectName("horizontalLayout_startReset")
        self.buttom_start = QtWidgets.QPushButton(self.widget_character)
        self.buttom_start.setObjectName("buttom_start")
        self.horizontalLayout_startReset.addWidget(self.buttom_start)
        self.buttom_reset = QtWidgets.QPushButton(self.widget_character)
        self.buttom_reset.setObjectName("buttom_reset")
        self.horizontalLayout_startReset.addWidget(self.buttom_reset)
        self.horizontalLayout.addLayout(self.horizontalLayout_startReset)
        self.gridLayout_2.addWidget(self.widget_character, 0, 0, 1, 1)
        self.tabWidget_character = QtWidgets.QTabWidget(Role)
        self.tabWidget_character.setMinimumSize(QtCore.QSize(620, 532))
        self.tabWidget_character.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabWidget_character.setObjectName("tabWidget_character")
        self.tabWidget_character_page_equipment = QtWidgets.QWidget()
        self.tabWidget_character_page_equipment.setToolTipDuration(1)
        self.tabWidget_character_page_equipment.setObjectName("tabWidget_character_page_equipment")
        self.tabWidget_equipment = QtWidgets.QTabWidget(self.tabWidget_character_page_equipment)
        self.tabWidget_equipment.setGeometry(QtCore.QRect(10, 10, 371, 301))
        self.tabWidget_equipment.setTabsClosable(False)
        self.tabWidget_equipment.setMovable(False)
        self.tabWidget_equipment.setObjectName("tabWidget_equipment")
        self.tabWidget_equipment_page_equipment = QtWidgets.QWidget()
        self.tabWidget_equipment_page_equipment.setObjectName("tabWidget_equipment_page_equipment")
        self.equipment_coat = QtWidgets.QPushButton(self.tabWidget_equipment_page_equipment)
        self.equipment_coat.setGeometry(QtCore.QRect(80, 30, 51, 51))
        self.equipment_coat.setObjectName("equipment_coat")
        self.equipment_earring = QtWidgets.QPushButton(self.tabWidget_equipment_page_equipment)
        self.equipment_earring.setGeometry(QtCore.QRect(240, 210, 51, 51))
        self.equipment_earring.setObjectName("equipment_earring")
        self.equipment_necklace = QtWidgets.QPushButton(self.tabWidget_equipment_page_equipment)
        self.equipment_necklace.setGeometry(QtCore.QRect(300, 90, 51, 51))
        self.equipment_necklace.setObjectName("equipment_necklace")
        self.equipment_shoulder = QtWidgets.QPushButton(self.tabWidget_equipment_page_equipment)
        self.equipment_shoulder.setGeometry(QtCore.QRect(20, 30, 51, 51))
        self.equipment_shoulder.setObjectName("equipment_shoulder")
        self.equipment_belt = QtWidgets.QPushButton(self.tabWidget_equipment_page_equipment)
        self.equipment_belt.setGeometry(QtCore.QRect(80, 90, 51, 51))
        self.equipment_belt.setObjectName("equipment_belt")
        self.equipment_weapon = QtWidgets.QPushButton(self.tabWidget_equipment_page_equipment)
        self.equipment_weapon.setGeometry(QtCore.QRect(240, 30, 51, 51))
        self.equipment_weapon.setObjectName("equipment_weapon")
        self.equipment_rings = QtWidgets.QPushButton(self.tabWidget_equipment_page_equipment)
        self.equipment_rings.setGeometry(QtCore.QRect(300, 150, 51, 51))
        self.equipment_rings.setObjectName("equipment_rings")
        self.equipment_pants = QtWidgets.QPushButton(self.tabWidget_equipment_page_equipment)
        self.equipment_pants.setGeometry(QtCore.QRect(20, 90, 51, 51))
        self.equipment_pants.setObjectName("equipment_pants")
        self.equipment_shoes = QtWidgets.QPushButton(self.tabWidget_equipment_page_equipment)
        self.equipment_shoes.setGeometry(QtCore.QRect(20, 150, 51, 51))
        self.equipment_shoes.setObjectName("equipment_shoes")
        self.equipment_magicShone = QtWidgets.QPushButton(self.tabWidget_equipment_page_equipment)
        self.equipment_magicShone.setGeometry(QtCore.QRect(300, 210, 51, 51))
        self.equipment_magicShone.setObjectName("equipment_magicShone")
        self.equipment_aider = QtWidgets.QPushButton(self.tabWidget_equipment_page_equipment)
        self.equipment_aider.setGeometry(QtCore.QRect(240, 150, 51, 51))
        self.equipment_aider.setObjectName("equipment_aider")
        self.equipment_bracelet = QtWidgets.QPushButton(self.tabWidget_equipment_page_equipment)
        self.equipment_bracelet.setGeometry(QtCore.QRect(240, 90, 51, 51))
        self.equipment_bracelet.setObjectName("equipment_bracelet")
        self.equipment_title = QtWidgets.QPushButton(self.tabWidget_equipment_page_equipment)
        self.equipment_title.setGeometry(QtCore.QRect(300, 30, 51, 51))
        self.equipment_title.setObjectName("equipment_title")
        self.Button_buff = QtWidgets.QPushButton(self.tabWidget_equipment_page_equipment)
        self.Button_buff.setGeometry(QtCore.QRect(20, 230, 75, 23))
        self.Button_buff.setObjectName("Button_buff")
        self.tabWidget_equipment.addTab(self.tabWidget_equipment_page_equipment, "")
        self.tabWidget_equipment_page_fashion = QtWidgets.QWidget()
        self.tabWidget_equipment_page_fashion.setObjectName("tabWidget_equipment_page_fashion")
        self.fashion_head = QtWidgets.QPushButton(self.tabWidget_equipment_page_fashion)
        self.fashion_head.setGeometry(QtCore.QRect(160, 40, 51, 51))
        self.fashion_head.setText("")
        self.fashion_head.setObjectName("fashion_head")
        self.fashion_hat = QtWidgets.QPushButton(self.tabWidget_equipment_page_fashion)
        self.fashion_hat.setGeometry(QtCore.QRect(220, 40, 51, 51))
        self.fashion_hat.setText("")
        self.fashion_hat.setObjectName("fashion_hat")
        self.fashion_face = QtWidgets.QPushButton(self.tabWidget_equipment_page_fashion)
        self.fashion_face.setGeometry(QtCore.QRect(280, 40, 51, 51))
        self.fashion_face.setText("")
        self.fashion_face.setObjectName("fashion_face")
        self.fashion_chest = QtWidgets.QPushButton(self.tabWidget_equipment_page_fashion)
        self.fashion_chest.setGeometry(QtCore.QRect(160, 100, 51, 51))
        self.fashion_chest.setText("")
        self.fashion_chest.setObjectName("fashion_chest")
        self.fashion_coat = QtWidgets.QPushButton(self.tabWidget_equipment_page_fashion)
        self.fashion_coat.setGeometry(QtCore.QRect(220, 100, 51, 51))
        self.fashion_coat.setText("")
        self.fashion_coat.setObjectName("fashion_coat")
        self.fashion_skin = QtWidgets.QPushButton(self.tabWidget_equipment_page_fashion)
        self.fashion_skin.setGeometry(QtCore.QRect(280, 100, 51, 51))
        self.fashion_skin.setText("")
        self.fashion_skin.setObjectName("fashion_skin")
        self.fashion_waist = QtWidgets.QPushButton(self.tabWidget_equipment_page_fashion)
        self.fashion_waist.setGeometry(QtCore.QRect(160, 160, 51, 51))
        self.fashion_waist.setText("")
        self.fashion_waist.setObjectName("fashion_waist")
        self.fashion_pants = QtWidgets.QPushButton(self.tabWidget_equipment_page_fashion)
        self.fashion_pants.setGeometry(QtCore.QRect(220, 160, 51, 51))
        self.fashion_pants.setText("")
        self.fashion_pants.setObjectName("fashion_pants")
        self.fashion_shoes = QtWidgets.QPushButton(self.tabWidget_equipment_page_fashion)
        self.fashion_shoes.setGeometry(QtCore.QRect(280, 160, 51, 51))
        self.fashion_shoes.setText("")
        self.fashion_shoes.setObjectName("fashion_shoes")
        self.fashion_halo = QtWidgets.QPushButton(self.tabWidget_equipment_page_fashion)
        self.fashion_halo.setGeometry(QtCore.QRect(90, 100, 51, 51))
        self.fashion_halo.setText("")
        self.fashion_halo.setObjectName("fashion_halo")
        self.fashion_weapon = QtWidgets.QPushButton(self.tabWidget_equipment_page_fashion)
        self.fashion_weapon.setGeometry(QtCore.QRect(90, 40, 51, 51))
        self.fashion_weapon.setText("")
        self.fashion_weapon.setObjectName("fashion_weapon")
        self.tabWidget_equipment.addTab(self.tabWidget_equipment_page_fashion, "")
        self.tabWidget_equipment_tab_pet = QtWidgets.QWidget()
        self.tabWidget_equipment_tab_pet.setObjectName("tabWidget_equipment_tab_pet")
        self.pet_pet = QtWidgets.QPushButton(self.tabWidget_equipment_tab_pet)
        self.pet_pet.setGeometry(QtCore.QRect(70, 30, 51, 51))
        self.pet_pet.setText("")
        self.pet_pet.setObjectName("pet_pet")
        self.pet_red = QtWidgets.QPushButton(self.tabWidget_equipment_tab_pet)
        self.pet_red.setGeometry(QtCore.QRect(250, 30, 51, 51))
        self.pet_red.setText("")
        self.pet_red.setObjectName("pet_red")
        self.pet_blue = QtWidgets.QPushButton(self.tabWidget_equipment_tab_pet)
        self.pet_blue.setGeometry(QtCore.QRect(250, 90, 51, 51))
        self.pet_blue.setText("")
        self.pet_blue.setObjectName("pet_blue")
        self.pet_green = QtWidgets.QPushButton(self.tabWidget_equipment_tab_pet)
        self.pet_green.setGeometry(QtCore.QRect(250, 150, 51, 51))
        self.pet_green.setText("")
        self.pet_green.setObjectName("pet_green")
        self.tabWidget_equipment.addTab(self.tabWidget_equipment_tab_pet, "")
        self.tabWidget_equipment_tab_medel = QtWidgets.QWidget()
        self.tabWidget_equipment_tab_medel.setObjectName("tabWidget_equipment_tab_medel")
        self.medel_medel = QtWidgets.QPushButton(self.tabWidget_equipment_tab_medel)
        self.medel_medel.setGeometry(QtCore.QRect(160, 90, 51, 51))
        self.medel_medel.setText("")
        self.medel_medel.setObjectName("medel_medel")
        self.medel_TopRight = QtWidgets.QPushButton(self.tabWidget_equipment_tab_medel)
        self.medel_TopRight.setGeometry(QtCore.QRect(220, 30, 51, 51))
        self.medel_TopRight.setText("")
        self.medel_TopRight.setObjectName("medel_TopRight")
        self.medel_BottomRight = QtWidgets.QPushButton(self.tabWidget_equipment_tab_medel)
        self.medel_BottomRight.setGeometry(QtCore.QRect(220, 150, 51, 51))
        self.medel_BottomRight.setText("")
        self.medel_BottomRight.setObjectName("medel_BottomRight")
        self.medel_BottomLeft = QtWidgets.QPushButton(self.tabWidget_equipment_tab_medel)
        self.medel_BottomLeft.setGeometry(QtCore.QRect(100, 150, 51, 51))
        self.medel_BottomLeft.setText("")
        self.medel_BottomLeft.setObjectName("medel_BottomLeft")
        self.medel_TopLeft = QtWidgets.QPushButton(self.tabWidget_equipment_tab_medel)
        self.medel_TopLeft.setGeometry(QtCore.QRect(100, 30, 51, 51))
        self.medel_TopLeft.setText("")
        self.medel_TopLeft.setObjectName("medel_TopLeft")
        self.tabWidget_equipment.addTab(self.tabWidget_equipment_tab_medel, "")
        self.scrollArea = QtWidgets.QScrollArea(self.tabWidget_character_page_equipment)
        self.scrollArea.setGeometry(QtCore.QRect(10, 320, 368, 200))
        self.scrollArea.setAutoFillBackground(True)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 366, 198))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_fireStrengthening = QtWidgets.QHBoxLayout()
        self.horizontalLayout_fireStrengthening.setObjectName("horizontalLayout_fireStrengthening")
        self.label_attribute_fireStrengthening = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_attribute_fireStrengthening.setObjectName("label_attribute_fireStrengthening")
        self.horizontalLayout_fireStrengthening.addWidget(self.label_attribute_fireStrengthening)
        self.attribute_fireStrengthening = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.attribute_fireStrengthening.setText("")
        self.attribute_fireStrengthening.setObjectName("attribute_fireStrengthening")
        self.horizontalLayout_fireStrengthening.addWidget(self.attribute_fireStrengthening)
        self.gridLayout.addLayout(self.horizontalLayout_fireStrengthening, 5, 0, 1, 1)
        self.horizontalLayout_lightStrengthening = QtWidgets.QHBoxLayout()
        self.horizontalLayout_lightStrengthening.setObjectName("horizontalLayout_lightStrengthening")
        self.label_attribute_lightStrengthening = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_attribute_lightStrengthening.setObjectName("label_attribute_lightStrengthening")
        self.horizontalLayout_lightStrengthening.addWidget(self.label_attribute_lightStrengthening)
        self.attribute_lightStrengthening = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.attribute_lightStrengthening.setText("")
        self.attribute_lightStrengthening.setObjectName("attribute_lightStrengthening")
        self.horizontalLayout_lightStrengthening.addWidget(self.attribute_lightStrengthening)
        self.gridLayout.addLayout(self.horizontalLayout_lightStrengthening, 7, 0, 1, 1)
        self.horizontalLayout_independentAttack = QtWidgets.QHBoxLayout()
        self.horizontalLayout_independentAttack.setObjectName("horizontalLayout_independentAttack")
        self.label_attritube_independentAttack = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_attritube_independentAttack.setObjectName("label_attritube_independentAttack")
        self.horizontalLayout_independentAttack.addWidget(self.label_attritube_independentAttack)
        self.attritube_independentAttack = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.attritube_independentAttack.setText("")
        self.attritube_independentAttack.setObjectName("attritube_independentAttack")
        self.horizontalLayout_independentAttack.addWidget(self.attritube_independentAttack)
        self.gridLayout.addLayout(self.horizontalLayout_independentAttack, 4, 0, 1, 2)
        self.horizontalLayout_spirit = QtWidgets.QHBoxLayout()
        self.horizontalLayout_spirit.setObjectName("horizontalLayout_spirit")
        self.label_attribute_spirit = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_attribute_spirit.setObjectName("label_attribute_spirit")
        self.horizontalLayout_spirit.addWidget(self.label_attribute_spirit)
        self.attribute_spirit = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.attribute_spirit.setText("")
        self.attribute_spirit.setObjectName("attribute_spirit")
        self.horizontalLayout_spirit.addWidget(self.attribute_spirit)
        self.gridLayout.addLayout(self.horizontalLayout_spirit, 1, 1, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_attribute_magicAttack = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_attribute_magicAttack.setObjectName("label_attribute_magicAttack")
        self.horizontalLayout_10.addWidget(self.label_attribute_magicAttack)
        self.attribute_magicAttack = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.attribute_magicAttack.setText("")
        self.attribute_magicAttack.setObjectName("attribute_magicAttack")
        self.horizontalLayout_10.addWidget(self.attribute_magicAttack)
        self.gridLayout.addLayout(self.horizontalLayout_10, 2, 1, 1, 1)
        self.horizontalLayout_stamina = QtWidgets.QHBoxLayout()
        self.horizontalLayout_stamina.setObjectName("horizontalLayout_stamina")
        self.label_attribute_stamina = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_attribute_stamina.setObjectName("label_attribute_stamina")
        self.horizontalLayout_stamina.addWidget(self.label_attribute_stamina)
        self.attribute_stamina = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.attribute_stamina.setText("")
        self.attribute_stamina.setObjectName("attribute_stamina")
        self.horizontalLayout_stamina.addWidget(self.attribute_stamina)
        self.gridLayout.addLayout(self.horizontalLayout_stamina, 1, 0, 1, 1)
        self.horizontalLayout_strength = QtWidgets.QHBoxLayout()
        self.horizontalLayout_strength.setObjectName("horizontalLayout_strength")
        self.label_attribute_strength = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_attribute_strength.setObjectName("label_attribute_strength")
        self.horizontalLayout_strength.addWidget(self.label_attribute_strength)
        self.attribute_strength = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.attribute_strength.setText("")
        self.attribute_strength.setObjectName("attribute_strength")
        self.horizontalLayout_strength.addWidget(self.attribute_strength)
        self.gridLayout.addLayout(self.horizontalLayout_strength, 0, 0, 1, 1)
        self.horizontalLayout_intelligence = QtWidgets.QHBoxLayout()
        self.horizontalLayout_intelligence.setObjectName("horizontalLayout_intelligence")
        self.label_attribute_intelligence = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_attribute_intelligence.setObjectName("label_attribute_intelligence")
        self.horizontalLayout_intelligence.addWidget(self.label_attribute_intelligence)
        self.attribute_intelligence = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.attribute_intelligence.setText("")
        self.attribute_intelligence.setObjectName("attribute_intelligence")
        self.horizontalLayout_intelligence.addWidget(self.attribute_intelligence)
        self.gridLayout.addLayout(self.horizontalLayout_intelligence, 0, 1, 1, 1)
        self.horizontalLayout_phyAttack = QtWidgets.QHBoxLayout()
        self.horizontalLayout_phyAttack.setSpacing(7)
        self.horizontalLayout_phyAttack.setObjectName("horizontalLayout_phyAttack")
        self.label_attribute_phyAttack = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_attribute_phyAttack.setObjectName("label_attribute_phyAttack")
        self.horizontalLayout_phyAttack.addWidget(self.label_attribute_phyAttack)
        self.attribute_phyAttack = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.attribute_phyAttack.setText("")
        self.attribute_phyAttack.setObjectName("attribute_phyAttack")
        self.horizontalLayout_phyAttack.addWidget(self.attribute_phyAttack)
        self.gridLayout.addLayout(self.horizontalLayout_phyAttack, 2, 0, 1, 1)
        self.horizontalLayout_iceStrengthening = QtWidgets.QHBoxLayout()
        self.horizontalLayout_iceStrengthening.setObjectName("horizontalLayout_iceStrengthening")
        self.label_attribute_iceStrengthening = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_attribute_iceStrengthening.setObjectName("label_attribute_iceStrengthening")
        self.horizontalLayout_iceStrengthening.addWidget(self.label_attribute_iceStrengthening)
        self.attribute_iceStrengthening = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.attribute_iceStrengthening.setText("")
        self.attribute_iceStrengthening.setObjectName("attribute_iceStrengthening")
        self.horizontalLayout_iceStrengthening.addWidget(self.attribute_iceStrengthening)
        self.gridLayout.addLayout(self.horizontalLayout_iceStrengthening, 5, 1, 1, 1)
        self.horizontalLayout_darkStrengthening = QtWidgets.QHBoxLayout()
        self.horizontalLayout_darkStrengthening.setObjectName("horizontalLayout_darkStrengthening")
        self.label_attribute_darkStrengthening = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_attribute_darkStrengthening.setObjectName("label_attribute_darkStrengthening")
        self.horizontalLayout_darkStrengthening.addWidget(self.label_attribute_darkStrengthening)
        self.attribute_darkStrengthening = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.attribute_darkStrengthening.setText("")
        self.attribute_darkStrengthening.setObjectName("attribute_darkStrengthening")
        self.horizontalLayout_darkStrengthening.addWidget(self.attribute_darkStrengthening)
        self.gridLayout.addLayout(self.horizontalLayout_darkStrengthening, 7, 1, 1, 1)
        self.horizontalLayout_basePhyAttack = QtWidgets.QHBoxLayout()
        self.horizontalLayout_basePhyAttack.setSpacing(7)
        self.horizontalLayout_basePhyAttack.setObjectName("horizontalLayout_basePhyAttack")
        self.label_attribute_basePhyAttack = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_attribute_basePhyAttack.setObjectName("label_attribute_basePhyAttack")
        self.horizontalLayout_basePhyAttack.addWidget(self.label_attribute_basePhyAttack)
        self.attribute_basePhyAttack = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.attribute_basePhyAttack.setText("")
        self.attribute_basePhyAttack.setObjectName("attribute_basePhyAttack")
        self.horizontalLayout_basePhyAttack.addWidget(self.attribute_basePhyAttack)
        self.gridLayout.addLayout(self.horizontalLayout_basePhyAttack, 3, 0, 1, 1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_attribute_magicAttack_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_attribute_magicAttack_2.setObjectName("label_attribute_magicAttack_2")
        self.horizontalLayout_11.addWidget(self.label_attribute_magicAttack_2)
        self.attribute_magicAttack_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.attribute_magicAttack_2.setText("")
        self.attribute_magicAttack_2.setObjectName("attribute_magicAttack_2")
        self.horizontalLayout_11.addWidget(self.attribute_magicAttack_2)
        self.gridLayout.addLayout(self.horizontalLayout_11, 3, 1, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.Options = QtWidgets.QWidget(self.tabWidget_character_page_equipment)
        self.Options.setGeometry(QtCore.QRect(390, 20, 201, 101))
        self.Options.setObjectName("Options")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Options)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_houseLevel_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_houseLevel_2.setObjectName("horizontalLayout_houseLevel_2")
        self.label_houseLevel_2 = QtWidgets.QLabel(self.Options)
        self.label_houseLevel_2.setObjectName("label_houseLevel_2")
        self.horizontalLayout_houseLevel_2.addWidget(self.label_houseLevel_2)
        self.comboBox_houseLevel_2 = QtWidgets.QComboBox(self.Options)
        self.comboBox_houseLevel_2.setObjectName("comboBox_houseLevel_2")
        self.horizontalLayout_houseLevel_2.addWidget(self.comboBox_houseLevel_2)
        self.verticalLayout.addLayout(self.horizontalLayout_houseLevel_2)
        self.horizontalLayout__advantureGroupLeve = QtWidgets.QHBoxLayout()
        self.horizontalLayout__advantureGroupLeve.setObjectName("horizontalLayout__advantureGroupLeve")
        self.label_advantureGroupLeve = QtWidgets.QLabel(self.Options)
        self.label_advantureGroupLeve.setObjectName("label_advantureGroupLeve")
        self.horizontalLayout__advantureGroupLeve.addWidget(self.label_advantureGroupLeve)
        self.comboBox_advantureGroupLevel = QtWidgets.QComboBox(self.Options)
        self.comboBox_advantureGroupLevel.setObjectName("comboBox_advantureGroupLevel")
        self.horizontalLayout__advantureGroupLeve.addWidget(self.comboBox_advantureGroupLevel)
        self.verticalLayout.addLayout(self.horizontalLayout__advantureGroupLeve)
        self.horizontalLayout_houseLevel = QtWidgets.QHBoxLayout()
        self.horizontalLayout_houseLevel.setObjectName("horizontalLayout_houseLevel")
        self.label_houseLevel = QtWidgets.QLabel(self.Options)
        self.label_houseLevel.setObjectName("label_houseLevel")
        self.horizontalLayout_houseLevel.addWidget(self.label_houseLevel)
        self.comboBox_houseLevel = QtWidgets.QComboBox(self.Options)
        self.comboBox_houseLevel.setObjectName("comboBox_houseLevel")
        self.horizontalLayout_houseLevel.addWidget(self.comboBox_houseLevel)
        self.verticalLayout.addLayout(self.horizontalLayout_houseLevel)
        self.line = QtWidgets.QFrame(self.tabWidget_character_page_equipment)
        self.line.setGeometry(QtCore.QRect(390, 110, 201, 31))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.widget = QtWidgets.QWidget(self.tabWidget_character_page_equipment)
        self.widget.setGeometry(QtCore.QRect(390, 130, 201, 251))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_damageIncrease = QtWidgets.QHBoxLayout()
        self.horizontalLayout_damageIncrease.setObjectName("horizontalLayout_damageIncrease")
        self.label_attribute_damageIncrease = QtWidgets.QLabel(self.widget)
        self.label_attribute_damageIncrease.setObjectName("label_attribute_damageIncrease")
        self.horizontalLayout_damageIncrease.addWidget(self.label_attribute_damageIncrease)
        self.attribute_damageIncrease = QtWidgets.QLabel(self.widget)
        self.attribute_damageIncrease.setText("")
        self.attribute_damageIncrease.setObjectName("attribute_damageIncrease")
        self.horizontalLayout_damageIncrease.addWidget(self.attribute_damageIncrease)
        self.verticalLayout_2.addLayout(self.horizontalLayout_damageIncrease)
        self.horizontalLayout_additionalDamageIncrease = QtWidgets.QHBoxLayout()
        self.horizontalLayout_additionalDamageIncrease.setObjectName("horizontalLayout_additionalDamageIncrease")
        self.label_attribute_additionalDamageIncrease = QtWidgets.QLabel(self.widget)
        self.label_attribute_additionalDamageIncrease.setObjectName("label_attribute_additionalDamageIncrease")
        self.horizontalLayout_additionalDamageIncrease.addWidget(self.label_attribute_additionalDamageIncrease)
        self.attribute_additionalDamageIncrease = QtWidgets.QLabel(self.widget)
        self.attribute_additionalDamageIncrease.setText("")
        self.attribute_additionalDamageIncrease.setObjectName("attribute_additionalDamageIncrease")
        self.horizontalLayout_additionalDamageIncrease.addWidget(self.attribute_additionalDamageIncrease)
        self.verticalLayout_2.addLayout(self.horizontalLayout_additionalDamageIncrease)
        self.horizontalLayout_critDamageIncrease = QtWidgets.QHBoxLayout()
        self.horizontalLayout_critDamageIncrease.setObjectName("horizontalLayout_critDamageIncrease")
        self.label_attribute_critDamageIncrease = QtWidgets.QLabel(self.widget)
        self.label_attribute_critDamageIncrease.setObjectName("label_attribute_critDamageIncrease")
        self.horizontalLayout_critDamageIncrease.addWidget(self.label_attribute_critDamageIncrease)
        self.attribute_critDamageIncrease = QtWidgets.QLabel(self.widget)
        self.attribute_critDamageIncrease.setText("")
        self.attribute_critDamageIncrease.setObjectName("attribute_critDamageIncrease")
        self.horizontalLayout_critDamageIncrease.addWidget(self.attribute_critDamageIncrease)
        self.verticalLayout_2.addLayout(self.horizontalLayout_critDamageIncrease)
        self.horizontalLayout_additionalCritDamageIncrease = QtWidgets.QHBoxLayout()
        self.horizontalLayout_additionalCritDamageIncrease.setObjectName("horizontalLayout_additionalCritDamageIncrease")
        self.label_attribute_additionalCritDamageIncrease = QtWidgets.QLabel(self.widget)
        self.label_attribute_additionalCritDamageIncrease.setObjectName("label_attribute_additionalCritDamageIncrease")
        self.horizontalLayout_additionalCritDamageIncrease.addWidget(self.label_attribute_additionalCritDamageIncrease)
        self.attribute_additionalCritDamageIncrease = QtWidgets.QLabel(self.widget)
        self.attribute_additionalCritDamageIncrease.setText("")
        self.attribute_additionalCritDamageIncrease.setObjectName("attribute_additionalCritDamageIncrease")
        self.horizontalLayout_additionalCritDamageIncrease.addWidget(self.attribute_additionalCritDamageIncrease)
        self.verticalLayout_2.addLayout(self.horizontalLayout_additionalCritDamageIncrease)
        self.horizontalLayout_additionalDamage = QtWidgets.QHBoxLayout()
        self.horizontalLayout_additionalDamage.setObjectName("horizontalLayout_additionalDamage")
        self.label_attribute_additionalDamage = QtWidgets.QLabel(self.widget)
        self.label_attribute_additionalDamage.setObjectName("label_attribute_additionalDamage")
        self.horizontalLayout_additionalDamage.addWidget(self.label_attribute_additionalDamage)
        self.attribute_additionalDamage = QtWidgets.QLabel(self.widget)
        self.attribute_additionalDamage.setText("")
        self.attribute_additionalDamage.setObjectName("attribute_additionalDamage")
        self.horizontalLayout_additionalDamage.addWidget(self.attribute_additionalDamage)
        self.verticalLayout_2.addLayout(self.horizontalLayout_additionalDamage)
        self.horizontalLayout_tendencyAdditionalDamage = QtWidgets.QHBoxLayout()
        self.horizontalLayout_tendencyAdditionalDamage.setObjectName("horizontalLayout_tendencyAdditionalDamage")
        self.label_attribute_tendencyAdditionalDamage = QtWidgets.QLabel(self.widget)
        self.label_attribute_tendencyAdditionalDamage.setObjectName("label_attribute_tendencyAdditionalDamage")
        self.horizontalLayout_tendencyAdditionalDamage.addWidget(self.label_attribute_tendencyAdditionalDamage)
        self.attribute_tendencyAdditionalDamage = QtWidgets.QLabel(self.widget)
        self.attribute_tendencyAdditionalDamage.setText("")
        self.attribute_tendencyAdditionalDamage.setObjectName("attribute_tendencyAdditionalDamage")
        self.horizontalLayout_tendencyAdditionalDamage.addWidget(self.attribute_tendencyAdditionalDamage)
        self.verticalLayout_2.addLayout(self.horizontalLayout_tendencyAdditionalDamage)
        self.horizontalLayout_strengthAndIntelligence = QtWidgets.QHBoxLayout()
        self.horizontalLayout_strengthAndIntelligence.setObjectName("horizontalLayout_strengthAndIntelligence")
        self.label_attribute_strengthAndIntelligence = QtWidgets.QLabel(self.widget)
        self.label_attribute_strengthAndIntelligence.setObjectName("label_attribute_strengthAndIntelligence")
        self.horizontalLayout_strengthAndIntelligence.addWidget(self.label_attribute_strengthAndIntelligence)
        self.attribute_strengthAndIntelligence = QtWidgets.QLabel(self.widget)
        self.attribute_strengthAndIntelligence.setText("")
        self.attribute_strengthAndIntelligence.setObjectName("attribute_strengthAndIntelligence")
        self.horizontalLayout_strengthAndIntelligence.addWidget(self.attribute_strengthAndIntelligence)
        self.verticalLayout_2.addLayout(self.horizontalLayout_strengthAndIntelligence)
        self.horizontalLayout_threeAttack = QtWidgets.QHBoxLayout()
        self.horizontalLayout_threeAttack.setObjectName("horizontalLayout_threeAttack")
        self.label_attribute_threeAttack = QtWidgets.QLabel(self.widget)
        self.label_attribute_threeAttack.setObjectName("label_attribute_threeAttack")
        self.horizontalLayout_threeAttack.addWidget(self.label_attribute_threeAttack)
        self.attribute_threeAttack = QtWidgets.QLabel(self.widget)
        self.attribute_threeAttack.setText("")
        self.attribute_threeAttack.setObjectName("attribute_threeAttack")
        self.horizontalLayout_threeAttack.addWidget(self.attribute_threeAttack)
        self.verticalLayout_2.addLayout(self.horizontalLayout_threeAttack)
        self.horizontalLayout_finalDamage = QtWidgets.QHBoxLayout()
        self.horizontalLayout_finalDamage.setObjectName("horizontalLayout_finalDamage")
        self.label_attribute_finalDamage = QtWidgets.QLabel(self.widget)
        self.label_attribute_finalDamage.setObjectName("label_attribute_finalDamage")
        self.horizontalLayout_finalDamage.addWidget(self.label_attribute_finalDamage)
        self.attribute_finalDamage = QtWidgets.QLabel(self.widget)
        self.attribute_finalDamage.setText("")
        self.attribute_finalDamage.setObjectName("attribute_finalDamage")
        self.horizontalLayout_finalDamage.addWidget(self.attribute_finalDamage)
        self.verticalLayout_2.addLayout(self.horizontalLayout_finalDamage)
        self.horizontalLayout_skillDamage = QtWidgets.QHBoxLayout()
        self.horizontalLayout_skillDamage.setObjectName("horizontalLayout_skillDamage")
        self.label_attribute_skillDamage = QtWidgets.QLabel(self.widget)
        self.label_attribute_skillDamage.setObjectName("label_attribute_skillDamage")
        self.horizontalLayout_skillDamage.addWidget(self.label_attribute_skillDamage)
        self.attribute_skillDamage = QtWidgets.QLabel(self.widget)
        self.attribute_skillDamage.setText("")
        self.attribute_skillDamage.setObjectName("attribute_skillDamage")
        self.horizontalLayout_skillDamage.addWidget(self.attribute_skillDamage)
        self.verticalLayout_2.addLayout(self.horizontalLayout_skillDamage)
        self.tabWidget_character.addTab(self.tabWidget_character_page_equipment, "")
        self.tabWidget_character_page_skill = QtWidgets.QWidget()
        self.tabWidget_character_page_skill.setObjectName("tabWidget_character_page_skill")
        self.tabWidget_skill = QtWidgets.QTabWidget(self.tabWidget_character_page_skill)
        self.tabWidget_skill.setGeometry(QtCore.QRect(0, 0, 841, 641))
        self.tabWidget_skill.setObjectName("tabWidget_skill")
        self.tabWidget_page_sp = QtWidgets.QWidget()
        self.tabWidget_page_sp.setObjectName("tabWidget_page_sp")
        self.tabWidget_skill.addTab(self.tabWidget_page_sp, "")
        self.tabWidget_page_tp = QtWidgets.QWidget()
        self.tabWidget_page_tp.setObjectName("tabWidget_page_tp")
        self.tabWidget_skill.addTab(self.tabWidget_page_tp, "")
        self.tabWidget_character.addTab(self.tabWidget_character_page_skill, "")
        self.tabWidget_character_page_damage = QtWidgets.QWidget()
        self.tabWidget_character_page_damage.setObjectName("tabWidget_character_page_damage")
        self.tabWidget_character.addTab(self.tabWidget_character_page_damage, "")
        self.gridLayout_2.addWidget(self.tabWidget_character, 1, 0, 1, 1)

        self.retranslateUi(Role)
        self.tabWidget_character.setCurrentIndex(0)
        self.tabWidget_equipment.setCurrentIndex(0)
        self.tabWidget_skill.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Role)

    def retranslateUi(self, Role):
        _translate = QtCore.QCoreApplication.translate
        Role.setWindowTitle(_translate("Role", "Form"))
        self.label_character.setText(_translate("Role", "角色"))
        self.cBox_character.setItemText(0, _translate("Role", "鬼剑士(男)"))
        self.cBox_character.setItemText(1, _translate("Role", "鬼剑士(女)"))
        self.cBox_character.setItemText(2, _translate("Role", "格斗家(男)"))
        self.cBox_character.setItemText(3, _translate("Role", "格斗家(女)"))
        self.cBox_character.setItemText(4, _translate("Role", "魔法师(男)"))
        self.cBox_character.setItemText(5, _translate("Role", "魔法师(女)"))
        self.cBox_character.setItemText(6, _translate("Role", "神枪手(男)"))
        self.cBox_character.setItemText(7, _translate("Role", "神枪手(女)"))
        self.cBox_character.setItemText(8, _translate("Role", "圣职者(男)"))
        self.cBox_character.setItemText(9, _translate("Role", "圣职者(女)"))
        self.cBox_character.setItemText(10, _translate("Role", "暗夜使者"))
        self.cBox_character.setItemText(11, _translate("Role", "守护者"))
        self.cBox_character.setItemText(12, _translate("Role", "外传"))
        self.cBox_character.setItemText(13, _translate("Role", "魔枪士"))
        self.cBox_character.setItemText(14, _translate("Role", "枪剑士"))
        self.label_profession.setText(_translate("Role", "职业"))
        self.label_level.setText(_translate("Role", "等级"))
        self.cbox_level.setItemText(0, _translate("Role", "95"))
        self.cbox_level.setItemText(1, _translate("Role", "90"))
        self.buttom_start.setText(_translate("Role", "开始"))
        self.buttom_reset.setText(_translate("Role", "重置"))
        self.Button_buff.setText(_translate("Role", "BUFF"))
        self.tabWidget_equipment.setTabText(self.tabWidget_equipment.indexOf(self.tabWidget_equipment_page_equipment), _translate("Role", "装备"))
        self.tabWidget_equipment.setTabText(self.tabWidget_equipment.indexOf(self.tabWidget_equipment_page_fashion), _translate("Role", "时装"))
        self.tabWidget_equipment.setTabText(self.tabWidget_equipment.indexOf(self.tabWidget_equipment_tab_pet), _translate("Role", "宠物"))
        self.tabWidget_equipment.setTabText(self.tabWidget_equipment.indexOf(self.tabWidget_equipment_tab_medel), _translate("Role", "勋章"))
        self.label_attribute_fireStrengthening.setText(_translate("Role", "火属性强化"))
        self.label_attribute_lightStrengthening.setText(_translate("Role", "光属性强化"))
        self.label_attritube_independentAttack.setText(_translate("Role", "独立攻击力(物理/魔法)"))
        self.label_attribute_spirit.setText(_translate("Role", "精神"))
        self.label_attribute_magicAttack.setText(_translate("Role", "魔法攻击"))
        self.label_attribute_stamina.setText(_translate("Role", "体力"))
        self.label_attribute_strength.setText(_translate("Role", "力量"))
        self.label_attribute_intelligence.setText(_translate("Role", "智力"))
        self.label_attribute_phyAttack.setText(_translate("Role", "物理攻击"))
        self.label_attribute_iceStrengthening.setText(_translate("Role", "冰属性强化"))
        self.label_attribute_darkStrengthening.setText(_translate("Role", "暗属性强化"))
        self.label_attribute_basePhyAttack.setText(_translate("Role", "基础物理攻击"))
        self.label_attribute_magicAttack_2.setText(_translate("Role", "基础魔法攻击"))
        self.label_houseLevel_2.setText(_translate("Role", "工会属性"))
        self.label_advantureGroupLeve.setText(_translate("Role", "冒险团等级"))
        self.label_houseLevel.setText(_translate("Role", "婚房等级"))
        self.label_attribute_damageIncrease.setText(_translate("Role", "黄字"))
        self.label_attribute_additionalDamageIncrease.setText(_translate("Role", "黄追"))
        self.label_attribute_critDamageIncrease.setText(_translate("Role", "爆伤"))
        self.label_attribute_additionalCritDamageIncrease.setText(_translate("Role", "爆追"))
        self.label_attribute_additionalDamage.setText(_translate("Role", "白字"))
        self.label_attribute_tendencyAdditionalDamage.setText(_translate("Role", "属性白字"))
        self.label_attribute_strengthAndIntelligence.setText(_translate("Role", "力量/智力"))
        self.label_attribute_threeAttack.setText(_translate("Role", "三攻"))
        self.label_attribute_finalDamage.setText(_translate("Role", "最终伤害"))
        self.label_attribute_skillDamage.setText(_translate("Role", "技能攻击力"))
        self.tabWidget_character.setTabText(self.tabWidget_character.indexOf(self.tabWidget_character_page_equipment), _translate("Role", "装备"))
        self.tabWidget_skill.setTabText(self.tabWidget_skill.indexOf(self.tabWidget_page_sp), _translate("Role", "SP"))
        self.tabWidget_skill.setTabText(self.tabWidget_skill.indexOf(self.tabWidget_page_tp), _translate("Role", "TP"))
        self.tabWidget_character.setTabText(self.tabWidget_character.indexOf(self.tabWidget_character_page_skill), _translate("Role", "技能"))
        self.tabWidget_character.setTabText(self.tabWidget_character.indexOf(self.tabWidget_character_page_damage), _translate("Role", "伤害"))

